language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - REACT_APP_URL=$API_URL npm run predeploy
deploy:
  provider: heroku
  skip_cleanup: true
  api_key: $API_KEY
  app: mev-gallery
  on:
    branch: master
